export const TICKET_TIER_ERRORS = {
  EVENT_NOT_FOUND: "EVENT_NOT_FOUND",
  FORBIDDEN: "FORBIDDEN",
  EVENT_NOT_EDITABLE: "EVENT_NOT_EDITABLE",
  SALE_END_AFTER_EVENT_START: "SALE_END_AFTER_EVENT_START",
  TIER_NAME_EXISTS: "TIER_NAME_EXISTS",
  EVENT_CANCELLED: "EVENT_CANCELLED",
  PRICE_CHANGE_BLOCKED: "PRICE_CHANGE_BLOCKED",
  LAST_ACTIVE_TIER: "LAST_ACTIVE_TIER",
  TIER_NOT_FOUND: "TIER_NOT_FOUND",
} as const;
