export const MESSAGES = {
  COMMON: {
    INTERNAL_SERVER_ERROR: "Internal server error",
    VALIDATION_FAILED: "Validation failed",
    INVALID_JSON_PAYLOAD: "Invalid JSON payload",
    DATA_RETRIVED_SUCCESS: "Data retrieved successfully",
  },
  AUTH: {
    REGISTER_SUCCESS: "Account registered successfully",
    LOGIN_SUCCESS: "Logged in successfully",
    PROFILE_RETRIEVED_SUCCESS: "Profile retrieved successfully",
    AUTHENTICATION_REQUIRED: "Authentication required",
    BEARER_TOKEN_REQUIRED:
      "Authentication required: provide Authorization Bearer token",
    TOKEN_EXPIRED: "Token expired",
    INVALID_TOKEN: "Invalid token",
    USER_NOT_FOUND_OR_INACTIVE: "User not found or inactive",
    ACCESS_DENIED: "Access denied",
    EMAIL_ALREADY_REGISTERED: "Email already registered",
    PHONE_ALREADY_REGISTERED: "Phone already registered",
    DEFAULT_USER_ROLE_NOT_CONFIGURED: "Default user role is not configured",
    INVALID_EMAIL_OR_PASSWORD: "Invalid email or password",
    USER_NOT_FOUND: "User not found",
  },
  UPLOAD: {
    INVALID_FILE_TYPE: "Only JPEG, PNG, and WebP images are allowed",
    FILE_TOO_LARGE: "Banner image must be 5 MB or smaller",
    BANNER_REQUIRED: "Banner image is required",
    BANNER_UPLOAD_FAILED: "Banner upload failed",
    BANNER_UPLOAD_SUCCESS: "Event banner uploaded successfully",
  },
  HEALTH: {
    API_RUNNING: "Event Ticket Booking API is running",
  },
  VENUE: {
    VENUE_CREATED_SUCCESS: "Venue created successfully",
    VENUES_RETRIEVED_SUCCESS: "Venues retrieved successfully",
    VENUE_DELETED_SUCCESS: "Venue deleted successfully",
    VENUE_DELETED_FAILED: "Venue deleted failed maybe it has active event",
  },
  USER: {
    USER_RETRIEVED_SUCCESS: "Users retrieved successfully",
    USER_UPDATE_SUCCESS: "User updated successfully",
    USER_STATUS_UPDATE_SUCCESS: "User status updated successfully",
    USER_ROLE_UPDATE_SUCCESS: "User role updated successfully",
  },
  EVENT: {
    EVENT_CREATED_SUCCESS: "Event created successfully",
    EVENT_UPDATED_SUCCESS: "Event updated successfully",
    EVENTS_RETRIEVED_SUCCESS: "Events retrieved successfully",
    EVENT_RETRIEVED_SUCCESS: "Event retrieved successfully",
    EVENT_NOT_FOUND: "Event not found",
    EVENT_STATUS_NOT_ACCEPTABLE: "Event status shold be rejected or approved",
  },
  EVENT_CATEGORY: {
    EVENT_CATEGORY_CREATED_SUCCESS: "Event category created successfully",
    EVENT_CATEGORIES_RETRIEVED_SUCCESS:
      "Event categories retrieved successfully",
    EVENT_CATEGORY_ALREADY_EXISTS: "Event category already exists",
  },
  TICKET_TIER: {
    TICKET_TIER_CREATED_SUCCESS: "Ticket tier created successfully",
    TICKET_TIERS_RETRIEVED_SUCCESS: "Ticket tiers retrieved successfully",
    TICKET_TIER_UPDATED_SUCCESS: "Ticket tier updated successfully",
    TICKET_TIER_DEACTIVATED_SUCCESS: "Ticket tier deactivated successfully",
    TICKET_TIER_NOT_FOUND: "Ticket tier not found",
    EVENT_NOT_EDITABLE: "Event is approved or cancelled",
    FORBIDDEN: "Not your event",
    SALE_END_AFTER_EVENT_START: "sale_ends_at must not exceed event.startsAt",
    TIER_NAME_EXISTS: "Name already used in this event",
  },
  BOOKING: {
    BOOKING_CREATED_SUCCESS: "Booking created successfully",
    INSUFFICIENT_TICKET_STOCK:
      "The requested number of tickets exceeds the available remaining stock.",
    BOOKING_NOT_FOUND: "Booking not found",
    BOOKING_PROCESSED: "Booking already processed",
    BOOKING_NOT_DONE: "Booking is not confirmed",
    RESERVATION_EXPIRED: "Reservation expired",
    BOOKINGS_RETRIEVED_SUCCESS: "Bookings retrieved successfully",
  },
  PAYMENT: {
    PAYMENT_CREATED_SUCCESS: "Payment created successfully",
    PAYMENT_NOT_SUCCESS: "Payment not found",
    PAYMENT_VERIFY_SUCCESS: "Payment verify successfully",
    PAYMENT_VERIFY_FAILED: "Invalid payment signature",
    ORDERID_NOT_EXIST: "razorpayOrderId not exist",
    PAYMENT_PAID_CANCELED: "Payment already paid or canceled",
    PAYMENT_MISMATCH: "Booking and payment mismatch",
  },
  TICKET: {
    TICKET_RETRIEVED_SUCCESS: "Ticket retrieved successfully",
    TICKET_CHECK_IN_SUCCESS: "Ticket check in successfully",
    TICKET_NOT_FOUND: "Ticket not found",
    TICKET_USED: "Ticket already checked in",
    TICKET_CANCELLED: "Ticket cancelled",
  },
  REFUND: {
    REFUND_REQUEST_CREATED: "Refund request created successfully",
    REFUND_PERIOD_ENDED: "Refund period ended",
    REFUND_PREVIEW_RETEIEVED: "Refund preview retrieved successfully",
    REFUND_APPROVED: "Refund approved successfully",
    REFUND_REJECTED: "Refund rejected successfully",
    REFUND_NOT_FOUND: "Refund not found",
    REFUND_PROCCESSED: "Refund already processed",
    REFUND_ALREADY_EXISTS: "Refund request already exists",
    BOOKING_NOT_ELIGIBLE_FOR_REFUND: "Booking is not eligible for refund",
    INVALID_INVENTORY_STATE: "Invalid inventory state",
    REFUND_FAILED: "Refund processing failed",
    REFUND_RETRIEVED_SUCCESS: "Refund retrieved successfully",
  },
};
